config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :posts do
    resources :comments
  end
 
  root "posts#index"
  
  get '/about', to: 'pages#about'
 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
  has_attached_file :image, styles: { medium: "700x500#", small: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
 
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
 
    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
     @posts = Post.all.order('created_at DESC')
  end
 
  def new
  @post = Post.new
  end
 
  def create
    @post = Post.new(post_params)
 
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body, :image))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <% if user_signed_in? %> 
  <p><%= link_to 'Delete', [comment.post, comment], 
                  method: :delete, 
                  class: "button", 
                  data: { confirm: 'Are you sure?' } %></p> 
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.svg" %>
        <% end %>
      </div>
 
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
 
      <ul>
       <li class="category">Social</li>
       <li><a href="#">Twitter</a></li>
       <li><a href="#">Instagram</a></li>
       <li><a href="#">Github</a></li>
       <li><a href="#">Email</a></li>
      </ul>
 
      <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
      <% end %>
    </div>
 
  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></button>
          <!-- <button class="button">Log Out</button> -->
        </div>
      <% end %>
    </div>
   
 
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
 
    <%= yield %>
  
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpg" %>
  </div>
 
  <div id="content">
    <h1>Hey, I'm Mackenzie Child</h1>
    <p>Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.</p>
    <p>This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.</p>
    <p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter <a href="http://twitter.com/mackenziechild">@MackenzieChild</a> or on the web at <a href="https://mackenziechild.me">mackenziechild.me</a>, and get my posts and exclusive content in your inbox by signing up for my newsletter <a href="http://eepurl.com/02olT">here</a>.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
<br>
  <br>
  <%= f.label :image, "image" %>
  <%= f.file_field :image %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_field :body %><br>
  <br>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
 
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <p><%= link_to (image_tag post.image.url(:small)) %></p>
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>
   <%= image_tag @post.image.url(:medium) %>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %> 
      | <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
   
  <p class="body">
    <%= @post.body %>

  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
      <%= render @post.comments %>
 
    <h3>Add a comment:</h3>
      <%= render "comments/form" %>
  </div>
</div>